from myproject import db
from myproject.models import Device, Menu, Product, BrewEvent
from datetime import datetime, time
# ## CREATE ALL THE TABLES Model -> DB table
db.create_all()

#
d1 = Device("xtMiBmyRpmA3",'K-Elite')
d2 = Device("1nh8GJiOmhMg",'K-Elite')
d3 = Device("KBGuaOuKOPtP",'K-Elite')
d4 = Device("HhCItdDglNEw",'K-Elite')
d5 = Device("3iQx4PgqmMnG",'K-Elite')
d6 = Device("zEVbGFRilOv0",'K-Elite')
d7 = Device("ph00q1l2lfwf",'K-Elite')
d8 = Device("9PHWCv3JJkcW",'K-Elite')
d9 = Device("HKsVqcVIEK6z",'Ninja')
d10 = Device("pOOOwOIKbCiZ",'Ninja')
d11 = Device("pWU0aMCrsrrA",'Ninja')
d12 = Device("wUp8b68MNoQu",'Ninja')
d13 = Device("qTE4xSgmbOYg",'Ninja')
d14 = Device("13gFGsRoheCI",'Ninja')
d15 = Device("28smn2ECz49Q",'Braun')
d16 = Device("zIwSGbcZX54B",'Braun')
d17 = Device("e5niYWhtQFt0",'Braun')
d18 = Device("rlwV7DQrbVMD",'Braun')
d19 = Device("TlysuGPSyRSf",'Braun')
d20 = Device("bGgYn6jAMJI7",'Braun')
#
db.session.add(d1)
db.session.add(d2)
db.session.add(d3)
db.session.add(d4)
db.session.add(d5)
db.session.add(d6)
db.session.add(d7)
db.session.add(d8)
db.session.add(d9)
db.session.add(d10)
db.session.add(d11)
db.session.add(d12)
db.session.add(d13)
db.session.add(d14)
db.session.add(d15)
db.session.add(d16)
db.session.add(d17)
db.session.add(d18)
db.session.add(d19)
db.session.add(d20)
#
#
m1 = Menu("Cold Brew", time(0,5,0))
m2 = Menu("Flat White", time(0,4,30))
m3 = Menu("Espresso", time(0,4,0))
m4 = Menu("Caffe Latte", time(0,3,30))

db.session.add(m1)
db.session.add(m2)
db.session.add(m3)
db.session.add(m4)
#
p1 = Product("INTENSO", 30, 29.99)
p2 = Product("BLACK", 60, 49.99)
p3 = Product("VANILLA", 10, 15.99)
p4 = Product("CHOCALATE", 20, 19.99)

db.session.add(p1)
db.session.add(p2)
db.session.add(p3)
db.session.add(p4)

# brew_time = datetime.now()
# be1 = BrewEvent(brew_time, 1, 1, 1)
# brew_time = datetime.now()
# be2 = BrewEvent(brew_time, 1, 13, 2)
# brew_time = datetime.now()
# be3 = BrewEvent(brew_time, 1, 1, 2)
# brew_time = datetime.now()
# be4 = BrewEvent(brew_time, 1, 13, 2)
# brew_time = datetime.now()
# be5 = BrewEvent(brew_time, 1, 11, 3)
# brew_time = datetime.now()
# be6 = BrewEvent(brew_time, 1, 13, 3)
# brew_time = datetime.now()
# # be7 = BrewEvent(brew_time, 1, 13, 4)
#
#
# db.session.add(be1)
# db.session.add(be2)
# db.session.add(be3)
# db.session.add(be4)
# db.session.add(be5)
# db.session.add(be6)
# db.session.add(be7)
# Order.query.delete()

db.session.commit()
